name: pa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - librosa
  - matplotlib
  - numpy
  - scipy
  - nltk
  - pip
  - pip:
      - textgrid
      - soundfile
      - pyttsx3
variables:
  NLTK_DATA: $CONDA_PREFIX/nltk_data