name: flask-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - librosa=0.11.0
  - matplotlib
  - numpy
  - scipy
  - nltk
  - pip
  - pip:
      - flask
      - flask-cors
      - werkzeug
      - soundfile
      - pydub
      - python-multipart